# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95962815c55912469a71913bdd3cf327591dd27147b1d3ec4609468a10d45b815a751ba10e110d49137350061acc1cd517a155b3bd64cb365ee19144d302fb1b

test:
  secret_key_base: 264ae46cfc534b0311e47fabf4cbcaf2d4197e4c3a02512b938fb0c1724944036650f6e53b0cda9357499bc0819b2e19465d048350489ef4ddb47c34b03b46db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
